"""수술DB 초기 시드 데이터 (루시드 동물병원 양식 기준).

각 수술마다 purpose_effect/procedure/complications/anesthesia_risk/
estimated_cost/hospitalization/expected_duration/notes 를 보유.
"""

SEED_SURGERIES = [
    # ──────── 일반외과 ────────
    {
        "name": "중성화수술(암컷) - 난소자궁적출술",
        "category": "일반외과",
        "purpose_effect": "암컷 반려동물의 생식능력 제거, 자궁축농증·유선종양(조기 중성화 시)·난소낭종·난소종양 등의 발생 위험을 현저히 낮춥니다.",
        "procedure": "전신마취 하에 복부 정중선(또는 측복부) 절개 후 난소와 자궁을 결찰·절제하고, 복막-근막-피하-피부 순으로 봉합.",
        "complications": "출혈, 봉합부 감염·열개, 요실금(대형견 일부), 난소잔존증후군, 마취 합병증. 일반적 예후는 양호.",
        "anesthesia_risk": "건강한 어린 환자는 위험도 낮음. 비만·심질환·고령 시 상승. 수술 전 혈액·심장검사 권장.",
        "estimated_cost": "30~60만원 (체중·난이도·입원 여부에 따라 변동)",
        "hospitalization": "입원 1일(당일 귀가 또는 1박). 7~14일째 실밥제거(내봉합 시 생략). 가정에서 넥카라 착용·산책 제한. 수술 후 1~2일 식욕·활력·배뇨·배변 상태 카카오톡 공유.",
        "expected_duration": "30~60분",
        "notes": "",
    },
    {
        "name": "중성화수술(수컷) - 거세술",
        "category": "일반외과",
        "purpose_effect": "번식능력 제거, 전립선질환·항문주위선종·고환종양·회음부 탈장 등의 예방. 공격성·마킹 등 행동 문제 완화에도 도움.",
        "procedure": "전신마취 하에 음낭 전방(또는 음낭) 절개 후 고환·정삭을 결찰·절제하고 피하·피부 봉합.",
        "complications": "출혈, 음낭혈종, 봉합부 감염, 마취 합병증. 잠복고환 시 복강내 접근 추가.",
        "anesthesia_risk": "일반적으로 위험도 낮음. 고령·기저질환 환자에서 상승.",
        "estimated_cost": "20~40만원 (잠복고환 동반 시 +10~20만원)",
        "hospitalization": "당일 또는 1박. 7~10일 넥카라·산책 제한. 수술 후 1~2일 상태 공유.",
        "expected_duration": "20~40분",
        "notes": "잠복고환(은고환)은 복강 절개 추가, 소요시간·회복기간 증가.",
    },
    {
        "name": "체표종양 절제술",
        "category": "일반외과",
        "purpose_effect": "피부·피하 종괴 완전 절제 후 병리조직검사로 양성/악성 확인. 악성 종양의 전이·재발 위험 감소.",
        "procedure": "안전한 절제연 확보해 종괴 제거 후 피하·피부 봉합. 절제물은 병리조직검사 의뢰.",
        "complications": "출혈, 봉합부 감염·열개, seroma, 재발, 악성 시 전이 가능성. 병리 결과에 따라 광범위 재절제·항암치료 필요할 수 있음.",
        "anesthesia_risk": "종괴 위치·크기에 따라 변동. 광범위 절제 시 마취 위험 상승.",
        "estimated_cost": "30~150만원 (종괴 크기·부위·병리검사 포함 여부에 따라)",
        "hospitalization": "당일 또는 1박. 7~14일 넥카라, 실밥 제거 전까지 목욕 금지. 병리결과는 5~10일 후 카카오톡 통보.",
        "expected_duration": "30분~2시간",
        "notes": "",
    },
    {
        "name": "탈장교정술(서혜부/제대/회음부)",
        "category": "일반외과",
        "purpose_effect": "복벽 결손부 봉합으로 복강내 장기의 돌출·감돈·괴사 예방.",
        "procedure": "탈장 부위 절개 → 내용물 정복 → 결손부 봉합(필요 시 메쉬 보강).",
        "complications": "재발, 봉합부 감염, 장 유착, 감돈 동반 시 장절제 추가로 예후 악화.",
        "anesthesia_risk": "일반적 위험. 장 괴사·감돈 시 상승.",
        "estimated_cost": "40~120만원 (부위·감돈 여부에 따라)",
        "hospitalization": "1~3일 입원. 2~4주 운동 제한, 복압 상승 활동 금지.",
        "expected_duration": "30~90분",
        "notes": "",
    },
    {
        "name": "치석제거술 및 발치",
        "category": "일반외과",
        "purpose_effect": "치석·치태·치주낭 감염원 제거로 치주염 진행 차단, 전신 감염 위험 감소. 보존 불가 치아 발치.",
        "procedure": "전신마취 → 치과방사선 촬영 → 초음파 스케일링·폴리싱 → 치주낭 측정 → 발치 대상 치아 외과적 발치 → 봉합.",
        "complications": "발치부 출혈, 구비누공(상악 견치), 하악골절(소형견 만성 치주염), 감염, 마취 합병증.",
        "anesthesia_risk": "고령 환자에서 마취 위험도 상승. 수술 전 검사 권장.",
        "estimated_cost": "30~120만원",
        "hospitalization": "당일 귀가. 7~14일 부드러운 사료, 처방 약물 복용. 양치는 구강점막 회복 후.",
        "expected_duration": "40분~2시간",
        "notes": "",
    },
    # ──────── 정형외과 ────────
    {
        "name": "슬개골 탈구 교정술(MPL)",
        "category": "정형외과",
        "purpose_effect": "슬개골을 활차구에 안정적으로 위치시켜 보행이상·통증·관절염 진행 억제. 운동능력 회복 기대.",
        "procedure": "활차구 성형술 + 경골조면 이식술(TTT) + 내측지대 해제 + 외측지대 강화 + (필요 시) 대퇴골·경골 교정절골술.",
        "complications": "재탈구(약 10~20%), 감염, 임플란트 관련 문제, 반대측 발병, 관절염 진행, 드물게 좌골신경 손상.",
        "anesthesia_risk": "중등도. 노령·소형견 기저질환(심장·기관허탈) 동반 시 주의.",
        "estimated_cost": "편측 150~250만원 / 양측 동시 250~400만원",
        "hospitalization": "2~5일 입원. 8주 엄격한 운동 제한(케이지 휴식), 점진적 재활. 4·8주차 방사선 추시. 미끄러운 바닥 금지.",
        "expected_duration": "60~120분",
        "notes": "grade에 따라 술식이 달라지며, 양측 동시 수술은 회복 부담 고려해 결정.",
    },
    {
        "name": "TPLO(경골고평부절골술)",
        "category": "정형외과",
        "purpose_effect": "전십자인대 파열 환자에서 경골 고평부 각도를 변경해 전방전위 기능적 제어. 통증 감소·보행회복·관절염 진행 억제.",
        "procedure": "경골 근위부 반월형 절골 → 회전 후 전용 플레이트 고정 → 반월판 검사 및 필요 시 부분절제.",
        "complications": "임플란트 감염·파손, 골유합 지연, 반월판 후기 손상(~10%), 경골결절 골절, 반대측 파열(약 30~50%).",
        "anesthesia_risk": "수술시간이 길어 마취 관리 중요. 체중 과다·고령 시 위험도 상승.",
        "estimated_cost": "편측 300~450만원",
        "hospitalization": "3~7일 입원. 8~12주 엄격한 운동 제한, 점진적 재활, 4·8·12주차 방사선 추시. 체중관리 필수.",
        "expected_duration": "90~150분",
        "notes": "중·대형견에 1차 선택. 소형견은 ELSS 고려.",
    },
    {
        "name": "골절 내고정술(IM pin / plate / ESF)",
        "category": "정형외과",
        "purpose_effect": "골절부를 해부학적으로 정복·고정해 골유합 도모. 조기 재활 가능.",
        "procedure": "골절부 접근·정복 → 핀/플레이트/나사/외고정장치 고정 → 봉합.",
        "complications": "감염(특히 개방골절), 임플란트 실패, 골유합 지연·불유합, 구획증후군, 관절강직.",
        "anesthesia_risk": "수술시간·출혈량에 따라 변동. 다발성 외상 환자는 안정화 후 시행.",
        "estimated_cost": "100~400만원 (부위·고정법에 따라)",
        "hospitalization": "3~7일 입원. 8~12주 운동 제한, 정기 방사선 추시, 재활운동.",
        "expected_duration": "60~180분",
        "notes": "",
    },
    {
        "name": "대퇴골두절제술(FHO)",
        "category": "정형외과",
        "purpose_effect": "통증 유발 부위 제거로 통증 해소와 기능적 보행 회복. 가관절 형성으로 일상생활 가능.",
        "procedure": "고관절 외측 접근 → 대퇴골두·경부 절단 → 관절낭·근육 봉합.",
        "complications": "근위축, 파행 잔존, 관절가동범위 감소, 감염.",
        "anesthesia_risk": "일반적 위험 수준.",
        "estimated_cost": "150~250만원",
        "hospitalization": "2~4일 입원. 조기 능동적 재활 중요 - 수영·수중트레드밀·점진적 운동 부하. 4·8주 추시.",
        "expected_duration": "45~90분",
        "notes": "중·소형견·고양이에 주 적응. 대형견은 THR 고려.",
    },
    # ──────── 연부조직외과 ────────
    {
        "name": "위장관 이물 제거술(위/장절개술)",
        "category": "연부조직외과",
        "purpose_effect": "위·소장 폐색 해소로 장 괴사·천공·복막염 예방. 조기 수술이 예후에 결정적.",
        "procedure": "정중개복 → 이물 위치 확인 → 위절개 또는 장절개로 이물 제거 → 이중층 봉합 → 복강세척 → 복벽 봉합. 괴사 시 장절제·문합 추가.",
        "complications": "봉합부 누출·복막염(3~7일째 주의), 재폐색, 패혈증, 유착성 장폐색, 봉합부 협착.",
        "anesthesia_risk": "탈수·전해질불균형·패혈증 동반 시 위험도 크게 상승. 수술 전 안정화 필수.",
        "estimated_cost": "150~500만원 (장절제 동반·입원일수에 따라)",
        "hospitalization": "3~7일 입원. 48~72시간 금식·수액, 단계적 유동식 재개. 넥카라 10~14일, 처방약 복용. 이물 섭취 환경 관리 필수.",
        "expected_duration": "60~180분",
        "notes": "linear foreign body(끈·실)는 여러 부위 장절개가 필요할 수 있어 특히 위험.",
    },
    {
        "name": "방광결석 제거술(방광절개술)",
        "category": "연부조직외과",
        "purpose_effect": "방광 내 결석 제거로 요폐색·방광점막 손상·혈뇨 해소. 성분분석에 따른 재발 예방 식이관리 가능.",
        "procedure": "하복부 정중절개 → 방광 노출 → 방광절개 → 결석 제거·요도 관류 → 이중층 봉합 → 복벽 봉합.",
        "complications": "재발(성분에 따라), 요누출, 감염, 방광수축력 일시적 저하.",
        "anesthesia_risk": "요독증·전해질이상 동반 시 위험도 상승. 수술 전 안정화 필요.",
        "estimated_cost": "80~200만원",
        "hospitalization": "2~5일 입원. 7~10일 넥카라, 처방 항생제·진통제, 성분분석 결과에 따른 처방식이·음수량 관리.",
        "expected_duration": "45~90분",
        "notes": "",
    },
    {
        "name": "비장적출술(Splenectomy)",
        "category": "연부조직외과",
        "purpose_effect": "비장 종양·염전·파열·면역매개성 질환에서 원인 제거. 응급 출혈 상황 생명 구조.",
        "procedure": "정중개복 → 비장 동·정맥 결찰(vessel sealing device) → 비장 적출 → 복강 점검 → 봉합.",
        "complications": "수술 중·후 출혈, 부정맥(VPC), 췌장염, 혈전색전증. 혈관육종 시 예후 불량.",
        "anesthesia_risk": "종양 파열·복강내출혈 동반 응급 시 매우 위험. 수혈 준비.",
        "estimated_cost": "200~500만원",
        "hospitalization": "3~7일 입원(ICU). 수액·진통제·심전도 모니터링, 넥카라. 병리결과에 따른 항암치료.",
        "expected_duration": "60~120분",
        "notes": "",
    },
    {
        "name": "간엽절제술(Liver lobectomy)",
        "category": "연부조직외과",
        "purpose_effect": "간엽의 종괴(종양·낭종·농양) 절제로 원인 제거 및 병리진단.",
        "procedure": "정중개복 → 해당 간엽 분리 → stapler 또는 결찰로 간엽 절제 → 지혈 확인 → 봉합.",
        "complications": "수술 중 대량출혈, 담즙누출, 응고장애, 수술 후 저혈당·저단백.",
        "anesthesia_risk": "응고장애·저혈압 위험. 수혈·응고검사 준비 권장.",
        "estimated_cost": "300~700만원",
        "hospitalization": "5~10일 입원(ICU). 영양관리, 단계적 식이 재개, 병리 결과 추시.",
        "expected_duration": "90~180분",
        "notes": "",
    },
    {
        "name": "회음부요도루설치술(PU, 수컷고양이)",
        "category": "연부조직외과",
        "purpose_effect": "재발성 요도폐색 수컷 고양이에서 영구적 개구부 형성으로 폐색 재발 현저히 감소, 삶의 질 개선.",
        "procedure": "복와위 → 회음부 절개 → 요도 분리 → 요도점막-피부 봉합으로 영구적 개구부 형성.",
        "complications": "협착(가장 흔함), 요실금, 상행감염, 개구부 출혈.",
        "anesthesia_risk": "요독증·고칼륨혈증 동반 시 매우 위험. 수술 전 안정화 필수.",
        "estimated_cost": "200~400만원",
        "hospitalization": "3~7일 입원. 넥카라, 처방식이·항생제, 페이퍼 타입 모래 권장.",
        "expected_duration": "45~90분",
        "notes": "",
    },
    # ──────── 응급·기타 ────────
    {
        "name": "제왕절개술(Cesarean section)",
        "category": "응급·기타",
        "purpose_effect": "자연분만이 어려운 난산·태아곤란·모체질환에서 모체와 태아의 안전한 분만.",
        "procedure": "정중개복 → 자궁체 절개 → 태아 분만·제대 결찰 → 자궁·복벽 봉합. 필요 시 난소자궁적출술 동시 시행.",
        "complications": "출혈, 태반 잔존, 자궁무력증, 신생아 저체온·저혈당, 감염, 드물게 모체 사망.",
        "anesthesia_risk": "모체·태아 모두에 영향. 신속·안전한 마취 중요. 태아 소생술 준비 필요.",
        "estimated_cost": "100~300만원",
        "hospitalization": "1~3일 입원. 모체 보온·통증관리, 유즙분비 확인, 신생아 체온·수유 관리.",
        "expected_duration": "45~90분",
        "notes": "난산 소견 확인 시 지체 없이 결정. 번식 계획 없으면 동시 중성화 권장.",
    },
    {
        "name": "위확장염전증(GDV) 교정술",
        "category": "응급·기타",
        "purpose_effect": "비틀어진 위를 정복·고정하여 재발 방지 및 생명 구조.",
        "procedure": "안정화 → 정중개복 → 위 감압·복위정복 → 위괴사 평가 → 비장평가 → 우측위고정술 → 봉합.",
        "complications": "사망률 10~30%, 위벽괴사, 재발(고정 미시행 시 80%+), 패혈증, 부정맥(VPC), DIC.",
        "anesthesia_risk": "쇼크·부정맥·전해질이상 동반 고위험. ICU 모니터링 필수.",
        "estimated_cost": "300~700만원",
        "hospitalization": "3~7일 ICU 입원. 심전도 모니터링, 단계적 식이, 넥카라, 소량 다회 급여, 식후 운동 제한.",
        "expected_duration": "90~180분",
        "notes": "예방적 위고정술은 대형견 중성화 시 동시 시행 가능.",
    },
    {
        "name": "자궁축농증 수술(난소자궁적출술)",
        "category": "응급·기타",
        "purpose_effect": "자궁 내 농양 제거로 패혈증 진행 차단, 생명 구조. 향후 재발 원천 차단.",
        "procedure": "수액·항생제 안정화 → 정중개복 → 자궁·난소 결찰·적출(파열 주의) → 복강세척 → 봉합.",
        "complications": "자궁파열·복막염, 수술 중 출혈, 급성신손상, 패혈증, 혈전색전증.",
        "anesthesia_risk": "패혈증·탈수·신기능저하 동반. 수술 전 혈액검사·안정화 필수.",
        "estimated_cost": "150~400만원",
        "hospitalization": "3~7일 입원. 신기능 추시, 넥카라, 식이 재개, 7~14일 안정.",
        "expected_duration": "60~120분",
        "notes": "폐쇄형(closed)일수록 파열 위험이 커 더욱 응급.",
    },
]


# ===================== 영상검사 DB 초기 시드 =====================
# 각 항목: name/category/modality/purpose_effect/procedure/complications/
#          contrast_type/sedation_note/post_care/expected_duration/estimated_cost/notes
# modality: "CT" / "MRI" / "CT,MRI"
# category: "신경" / "복부" / "흉부" / "근골격" / "치과" / "종양" / "혈관" / "기타"

SEED_IMAGING = [
    {
        "name": "복부 CT (조영)",
        "category": "복부",
        "modality": "CT",
        "purpose_effect": "간·비장·신장·부신·췌장·림프절·장관·혈관 등 복부 장기의 구조적 이상, 종양 위치·크기·전이·혈관 침범 여부를 정밀 평가합니다. 수술 계획 수립이나 종양 병기 결정에 필수적입니다.",
        "procedure": "전신마취 후 복부 CT 촬영. 조영제(Iodine) 정맥주입 후 동맥기·정맥기·지연기 다상 이미지 획득. 총 촬영 시간 15~30분, 마취 준비 포함 총 1~2시간.",
        "complications": "① 전신마취 합병증(호흡·순환 저하, 드물게 사망 0.1~0.5%). ② 조영제 알레르기·과민반응(드묾, 0.1~1%), 급성신손상(기저 신장병 있을 때 위험↑). ③ 방사선 피폭(1회 검사량은 생물학적 유해 수준 미만이지만 임신묘·임신견은 제외).",
        "contrast_type": "Iodine (요오드화 조영제)",
        "sedation_note": "전신마취 필수 — 움직임 없어야 해상도 확보. 사전 12시간 금식·4시간 금수. 심·신장 기능 혈액검사 권장.",
        "post_care": "마취 회복실에서 2~4시간 관찰(체온·혈압·의식). 퇴원 후 24시간 수분 섭취 충분히(조영제 배출). 검사 부위 이상 시 즉시 연락.",
        "expected_duration": "15~30분 (마취 포함 총 1~2시간)",
        "estimated_cost": "60~120만원 (조영제·마취 포함)",
        "notes": "",
    },
    {
        "name": "흉부 CT",
        "category": "흉부",
        "modality": "CT",
        "purpose_effect": "폐·기관지·종격동·심장·흉벽·흉막·림프절의 병변을 평가합니다. 폐종양·전이·진균증·기관지 협착·흉수 원인 규명 등에 사용.",
        "procedure": "전신마취 후 흉부 CT. 필요 시 조영제 정맥주입. 10~20분 촬영.",
        "complications": "전신마취 위험, 흉부 질환 환자는 호흡부전 위험↑, 방사선 피폭.",
        "contrast_type": "선택적 (Iodine)",
        "sedation_note": "전신마취 필수. 호흡기 불안정 환자는 보정 마취로 조정. 금식 12시간.",
        "post_care": "마취 회복 후 호흡수·혈중산소포화도 모니터링. 흉부 상태 변화 시 재진.",
        "expected_duration": "10~20분",
        "estimated_cost": "50~100만원",
        "notes": "폐전이 평가 시 고해상도 모드 촬영.",
    },
    {
        "name": "뇌 MRI (조영)",
        "category": "신경",
        "modality": "MRI",
        "purpose_effect": "뇌 실질·뇌실·뇌막·뇌혈관·뇌신경 평가. 뇌종양·뇌수막염·뇌경색·뇌염·수두증·구조이상 등의 진단에 가장 정밀한 검사입니다.",
        "procedure": "전신마취 후 MRI 촬영. 가돌리늄 조영제 정맥주입 후 전·후 이미지 획득. 30~60분 소요.",
        "complications": "① 전신마취(특히 장시간) 합병증. ② 가돌리늄 조영제 부작용(드묾) — 신부전 환자는 전신 신원성 섬유증(NSF) 위험. ③ 금속 삽입물 있는 환자 절대 금기.",
        "contrast_type": "Gadolinium (가돌리늄)",
        "sedation_note": "전신마취 필수(환자가 움직이면 촬영 불가). 장시간(30분~1시간) 정치 자세라 심·호흡 모니터링 철저. 체내 금속 이식물(심박동기·인공관절 등) 있으면 사전 고지.",
        "post_care": "장시간 마취로 회복 시간 김(4~6시간). 물 충분히 섭취. 신경증상 변화 관찰.",
        "expected_duration": "30~60분",
        "estimated_cost": "100~180만원",
        "notes": "뇌 MRI는 보통 조영 전·후 세트로 촬영.",
    },
    {
        "name": "척추 MRI",
        "category": "신경",
        "modality": "MRI",
        "purpose_effect": "추간판 탈출증(디스크), 척수 종양, 척수 경색, 척수막염, 선천성 기형 등 척수·척추 병변 진단의 최적 검사.",
        "procedure": "전신마취 후 병변 의심 척추 분절(경추/흉추/요추) MRI 촬영. 30~50분.",
        "complications": "전신마취 합병증. 척수 병변 심한 경우 마취 중 악화 가능성(드묾).",
        "contrast_type": "선택적 (Gadolinium)",
        "sedation_note": "전신마취 필수. 하반신 마비 환자는 체위 잡기 주의.",
        "post_care": "마취 회복 + 신경증상 모니터링. 디스크 진단 시 바로 수술·스테로이드 치료 결정.",
        "expected_duration": "30~50분",
        "estimated_cost": "90~160만원",
        "notes": "",
    },
    {
        "name": "CT 혈관조영술 (Angio-CT)",
        "category": "혈관",
        "modality": "CT",
        "purpose_effect": "동맥·정맥의 해부·병변을 3D로 평가. 간문맥단락(PSS), 동정맥 기형, 혈관 침범 종양 등의 진단·수술 계획에 필수.",
        "procedure": "전신마취 후 Iodine 조영제 고속 정맥주입하며 빠른 연속 촬영. 3D 재구성.",
        "complications": "일반 CT와 동일 + 조영제 양 많아 신장 부담 증가.",
        "contrast_type": "Iodine (고용량)",
        "sedation_note": "신장 기능 검사(BUN·CREA·SDMA) 반드시 확인 후 진행. 수액 선처치로 신손상 예방.",
        "post_care": "수액 유지 24시간. 배뇨량 관찰.",
        "expected_duration": "20~40분",
        "estimated_cost": "80~150만원",
        "notes": "",
    },
    {
        "name": "복부 MRI (조영)",
        "category": "복부",
        "modality": "MRI",
        "purpose_effect": "간·담도·췌장 등의 연부조직 해상도가 높은 병변 평가. 담관폐쇄·간종양 감별·췌장염 평가 등에 CT 보완용.",
        "procedure": "전신마취 후 복부 MRI. Gadolinium 조영제 사용. 40~60분.",
        "complications": "장시간 마취·조영제 부작용.",
        "contrast_type": "Gadolinium",
        "sedation_note": "전신마취 + 체온 유지 중요.",
        "post_care": "마취 회복 후 수분 보충.",
        "expected_duration": "40~60분",
        "estimated_cost": "110~180만원",
        "notes": "",
    },
    {
        "name": "귀·두부 MRI",
        "category": "신경",
        "modality": "MRI",
        "purpose_effect": "중이염·내이염·귀 종양·전정 질환·비강 종양·안구 후방 병변 등 두부 연부조직 병변 평가.",
        "procedure": "전신마취 후 두부 MRI. 20~40분.",
        "complications": "전신마취 합병증.",
        "contrast_type": "선택적 (Gadolinium)",
        "sedation_note": "전신마취 필수.",
        "post_care": "마취 회복 관찰.",
        "expected_duration": "20~40분",
        "estimated_cost": "80~140만원",
        "notes": "",
    },
    {
        "name": "치과·악관절 CT",
        "category": "치과",
        "modality": "CT",
        "purpose_effect": "치근 병변·턱뼈 종양·악관절 이상·상악동 병변 등의 3D 평가. 일반 치과 방사선으로 파악하기 어려운 병변을 입체적으로 확인.",
        "procedure": "전신마취 후 두경부 CT. 10~15분 촬영. 동시에 스케일링·발치 진행하는 경우 많음.",
        "complications": "전신마취 합병증.",
        "contrast_type": "비사용 (일반적으로)",
        "sedation_note": "치과 치료와 함께 진행 시 마취 시간 길어짐.",
        "post_care": "치과 처치 후 연식 급여 권장.",
        "expected_duration": "10~15분 (촬영만)",
        "estimated_cost": "40~80만원",
        "notes": "치과 스케일링·발치와 함께 진행하면 효율적.",
    },
    {
        "name": "종양 병기 결정 CT (흉·복부)",
        "category": "종양",
        "modality": "CT",
        "purpose_effect": "악성 종양 환자의 전신 전이 여부 확인(폐·간·림프절·골격). 치료 방침(수술 vs 항암 vs 완화) 결정을 위한 필수 검사.",
        "procedure": "전신마취 후 흉부+복부 CT를 연속 촬영. 조영제 사용. 총 20~40분.",
        "complications": "전신마취 + 조영제 부작용. 방사선 피폭 1회 검사당 영향 미미.",
        "contrast_type": "Iodine",
        "sedation_note": "종양 환자는 전신 상태 약함 — 사전 혈액·심장검사 필수.",
        "post_care": "결과에 따라 항암·수술·완화 결정 상담.",
        "expected_duration": "20~40분",
        "estimated_cost": "100~180만원",
        "notes": "",
    },
    {
        "name": "사지·관절 MRI",
        "category": "근골격",
        "modality": "MRI",
        "purpose_effect": "인대·연골·건·근육·골수 병변 평가. 십자인대 부분 파열·연골손상·근육 종양 등 X선·CT로 구분 어려운 연부조직 병변에 적합.",
        "procedure": "전신마취 후 해당 관절·사지 MRI. 20~40분.",
        "complications": "전신마취.",
        "contrast_type": "선택적 (Gadolinium)",
        "sedation_note": "전신마취 필수.",
        "post_care": "마취 회복 + 진단 결과에 따라 치료 계획.",
        "expected_duration": "20~40분",
        "estimated_cost": "80~140만원",
        "notes": "",
    },
]
